### PR TITLE
Removed unneeded _this_ keywords

### PR DESCRIPTION
**Pull request by dinitrogen-tetroxide**
Removed appropriate occurrences of the _this_ keyword. Left the _this_ keyword in places with ambiguity.

Issue #305

### CODE REVIEW

**Comment by dinitrogen-tetroxide** [comment]
Since there's been changes to the Hacktoberfest requirements, would you mind giving this the label 'hacktoberfest-accepted' if you find that it is worth?

**Review by yallen011 — CHANGES_REQUESTED** [review]
The changes look good. Just add yourself to the CONTRIBUTORS.md file and I will accept

**Comment by dinitrogen-tetroxide** [comment]
> The changes look good. Just add yourself to the CONTRIBUTORS.md file and I will accept

Alright, I'll do that.

**Review by yallen011 — APPROVED** [review]
LGTM 👍

**Pull request merged**
