### PR TITLE
Updated 2 test files and CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by nikolatechie**
Rollback changes from files <code>AccountClient.java</code> and <code>PrefixPricingEndpoint.java</code>, pushed changes to 2 test files and added myself to <code>CONTRIBUTORS.md</code>
#339

### CODE REVIEW

**Comment by sirNikolai** [comment]
If this is in relation to #342 then I think it might be more prudent to wait to see if the core team decide to actually treat this as a required refactor or not. Also if they decide to move to JUnit 5 it would be a more substantial (but possibly QoL necessary) lift.

If you are removing the deprecated imports, I found 5 files that actually have them.
image

**Comment by yallen011** [comment]
Closing this since these changes should be added to PR #339

**Comment by yallen011** [comment]
reopened this @nikolatechie can you pull the latest changes, rebase onto master( `git rebase master`) from the `this_keyword` branch and do a force push and I will merge the changes.

**Comment by yallen011** [comment]
@nikolatechie did you want me to merge these changes? If so, I am unable to repoen them but maybe you can. Try reopening if you would like the changes to be merged if not we can keep it closed.

**Comment by nikolatechie** [comment]
@yallen011  Force push closed this automatically. I have allowed edits by maintainers so you might be able to reopen since I'm not. If you can't, then we can keep it closed.

**Pull request closed without merging**
