### PR TITLE
Removed unnecessary "this" keywords in two files

### PR DESCRIPTION
**Pull request by nikolatechie**
Removed unnecessary "this" keywords in files AccountClient.java and PrefixPricingEndpoint.java.
Issue: #305

### CODE REVIEW

**Review by yallen011 — CHANGES_REQUESTED** [review]
Can you remove the `this` keyword from line 31 in PrefixPricingMethodTest.java. Also, if you are up for it, can you removed the `import junit.framework.Assert` from line 22 in `AccountClientTest.java` class since it is deprecated, and replace all the `Assert.assertEquals` to `assertEquals` this will cause them to use the `import static org.junit.Assert.assertEquals` static import instead.

**Comment by nikolatechie** [comment]
> Can you remove the `this` keyword from line 31 in PrefixPricingMethodTest.java. Also, if you are up for is, can you removed the `import junit.framework.Assert` from line 22 in `AccountClientTest.java` class since it is deprecated, and replace all the `Assert.assertEquals` to `assertEquals` this will cause them to use the `import static org.junit.Assert.assertEquals` static import instead.

Sure, will be done today.

**Comment by yallen011** [comment]
Awesome, the changes look good. 
Now when you get a chance, run the following commands before adding yourself to the CONTRIBUTORS.md file and you will be all set for us to merge your PR. Run the following commands in your local repo:

1. `git fetch upstream`

2. `git checkout master` 

3. `git merge upstream/master` 

4. `git checkout this_keyword`

5. `git rebase master`

After you have rebased your branch with master to make sure you have the latest changes, add yourself to the CONTRIBUTORS.md file then push that change and you will be all set 😃

**Comment by yallen011** [comment]
@nikolatechie I have good news and bad news, 2 of the changes you submitted were already claimed by another user in the #305 issue. I asked that you add a comment with the files that you would like to work on so that people didn't end up working on the same files. The other user claimed **AccountClient.java** and **PrefixPricingMethodTest.java** already so I can't accept those as part of your PR but I can accept the 2 test files you worked on so all is well in that regards. To fix your PR, you would need to rollback those 2 files after you run the rebase command in number 5 of my previous comment. Then you could run the following commands to revert the files:
`git checkout @ -- src/main/java/com/vonage/client/account/AccountClient.java`
`git checkout @ -- src/main/java/com/vonage/client/account/PrefixPricingEndpoint.java`

After that, you can run the following commands before adding yourself to the CONTRIBUTORS.md file and you will be all set for us to merge your PR. Run the following commands in your local repo:

git fetch upstream

git checkout master

git merge upstream/master

git checkout this_keyword

git rebase master

After you have rebased your branch with master to make sure you have the latest changes, add yourself to the CONTRIBUTORS.md file then push that change and you will be all set 😃. When you have pushed the change, make sure to click on the refresh icon by my name under Reviewers so that I will be notified that you have pushed the change are you are ready for review again.

**Comment by nikolatechie** [comment]
Made those changes and added myself to <code>CONTRIBUTORS.md</code> here #344.

**Comment by yallen011** [comment]
Hi @nikolatechie the changes from #344 should be made in this pull request. If you need to make a change, you don't have to create a new PR to do so. You just make the change in your branch, then follow steps 1-5 that I mentioned in my last comment to get the latest changes from master, run the `gradle build` command to make sure the build still work and the test are still passing, then run the `git push origin this_keyword` command to push the code up to GitHub. When you have pushed the change, make sure to click on the refresh icon by my name under Reviewers so that I will be notified that you have pushed the change are you are ready for review again.

**Comment by nikolatechie** [comment]
@yallen011 I did that before, but I'm getting errors. Also, at the top of this page, it says I'm trying to merge from <code>unkown repository</code>, so since it didn't work I created new PR with needed updates. Maybe it would be better to close this PR and reopen #344.

**Comment by yallen011** [comment]
Closing. Added in the 6.0.0 release

**Pull request closed without merging**
