### PR TITLE
Introduce Lombok for account types with focus on toString

### PR DESCRIPTION
**Pull request by michel-zimmer**
I've started adding Lombok Annotations in the `account` package to give an idea, what it can look like. See #134 

## Contribution Checklist
* [x] Unit tests! (nothing added because no requirement changed, only refactoring)
* [x] Updated [CHANGELOG.md](CHANGELOG.md) (nothing added because no requirement changed, only refactoring)
* [x] My name is in [CONTRIBUTORS.md](CONTRIBUTORS.md)

### CODE REVIEW

**Comment by michel-zimmer** [comment]
Yes, one could go much further using Lombok, but I would like to hear opinions first.

Also I didn't fully understand, which classes are used for serializing, which for deserializing and which for both, and I wanted to make sure, nothing is broken, because the serialization is not fully covered using unit tests. If that is clear, one could go ahead and make a lot of fields final and when they are final, one could also go ahead and use `@Value` from Lombok, which adds all the boiler plate code at once (`equals`, `hashCode`, `toString`, getters and possibly even possibly constructors).

**Comment by michel-zimmer** [comment]
See my comment here, why I didn't push updates to the PR: https://github.com/Vonage/vonage-java-sdk/issues/134#issuecomment-704050296

**Comment by yallen011** [comment]
Hi @michel-zimmer sorry it has taken so long to get to your PR, we had a bit of a backup do to Hacktoberfest. We are ready to finish reviewing your PR but can you pull down the latest from master, rebase your branch onto master, and do a force push to fix the merge conflicts. Thanks

**Comment by michel-zimmer** [comment]
I cannot push to the branch again because this PR has been unlinked from my fork. I've asked GitHub support but apparently they cannot reconnect the PR. This means I'll have to close the PR. If I find the time I'll create a new one in the future.

**Pull request closed without merging**
