### PR TITLE
 Remove unnecessary references to the "this" keyword

### PR DESCRIPTION
**Pull request by SanchitaMishra170676**
issue #305
 Removed unnecessary references to the "this" keyword in SmsClient.java

### CODE REVIEW

**Comment by yallen011** [comment]
Hi @SanchitaMishra170676 the build is failing please pull down the latest code from master, rebase your branch with master then run the `gradle build` command in the terminal or in your IDE and fix the errors. Once you have done that, push the fixed code and hit the refresh icon next to my name under **Reviewers** at the top right to notify me that the changes have been made. If you don't now yow to pull down the latest code and rebase it with master branch please let me know.

**Review by yallen011 — CHANGES_REQUESTED** [review]
Hi @SanchitaMishra170676 the build is failing please pull down the latest code from master, rebase your branch with master then run the `gradle build` command in the terminal or in your IDE and fix the errors. Once you have done that, push the fixed code and hit the refresh icon next to my name under Reviewers at the top right to notify me that the changes have been made. If you don't now yow to pull down the latest code and rebase it with master branch please let me know.

**Comment by yallen011** [comment]
This PR has gone stale. Closing

**Comment by SanchitaMishra170676** [comment]
Respected sir/ ma'am
Please assign the issue to someone else.
Thanks & Regards
Sanchita Mishra

**Pull request closed without merging**
