### PR TITLE
Removed @auth 

### PR DESCRIPTION
**Pull request by error404-sp**

### CODE REVIEW

**Comment by yallen011** [comment]
This change has already been submitted. Sorry, but there are a few other Hacktoberfest issues you can contribute to. If you see one that you would like to work in but need a little help with it. please comment in the issue and I will be happy to assist.

**Comment by yallen011** [comment]
Hi @error404-sp if you would like, you can submit a PR for the SmsClient.java file instead. It has recently become available.

**Comment by error404-sp** [comment]
Thank you . I will give it a try

**Comment by error404-sp** [comment]
I have submitted the PR. Would love to work on more issues
https://github.com/Vonage/vonage-java-sdk/pull/348

**Pull request closed without merging**
